### ISSUE TITLE
Stopped working on Version 7.3 

### ISSUE THREAD

**Issue by Shozuke** [ThilinaHewagama/AutoIndentWithSave#11]
Since last update, AutoIndentWithSave stopped working

**Comment by GINNOV** [comment]
while this gets fixed: If you add/remove the adding (without rebooting xcode) it will work again (flaky but it does)

**Comment by chamoda** [comment]
@kywix you mean just the plugin? I tried but did not work.

**Comment by GINNOV** [comment]
Yes, that is what I meant. I really look forward to an update.
